
const badWordsList = [
    "buceta",
    "bucetinha",
    "bucetão",
    "bucetuda",
    "piroca",
    "hitler",
    "piranha",
    "judeus",
    "mato",
    "matar",
    "morrer",
    "churrascar",
    "fuher",
    "reich",
    "estuprar",
    "nazista",
    "molestar",
    "fascista",
    "fascismo",
    "cp",
    "puta",
    "putinha",
    "putão",
    "putuda",
    "caralho",
    "caralhão",
    "caralhuda",
    "merda",
    "merdinha",
    "merdão",
    "merduda",
    "cuzinho",
    "cuzão",
    "cuzuda",
    "xota",
    "xotinha",
    "xotão",
    "xotuda",
    "bosta",
    "bostinha",
    "bostão",
    "bostuda",
    "fodase",
    "foda-se",
    "foder",
    "foda",
    "fudendo",
    "fudida",
    "fudido",
    "fudida",
    "fudendo",
    "porno",
    "porra",
    "desgraca",
    "mussolini",
    "bolsonaro",
    "lula",
    "dilma",
    "temer",
    "mito",
    "genocida",
    "corno",
    "corna",
    "aborto",
    "ânus",
    "macaco",
    "bucet4",
    "se mata",
    "smt",
    "kys",
    "porr4",
    "amador",
    "aranha",
    "ariano",
    "balalao",
    "bastardo",
    "bicha",
    "biscate",
    "bissexual",
    "boceta",
    "boob",
    "bosta",
    "braulio de borracha",
    "bumbum",
    "burro",
    "cabrao",
    "cacete",
    "cagar",
    "camisinha",
    "caralho",
    "cerveja",
    "chochota",
    "chupar",
    "clitoris",
    "cocaína",
    "coito",
    "colhoes",
    "comer",
    "cona",
    "consolo",
    "corno",
    "dar o rabo",
    "dum raio",
    "esporra",
    "fecal",
    "filho da puta",
    "foda",
    "foder",
    "gozar",
    "grelho",
    "heroína",
    "homoerótico",
    "inferno",
    "lolita",
    "mama",
    "merda",
    "paneleiro",
    "passar um cheque",
    "pau",
    "peidar",
    "pênis",
    "pinto",
    "porra",
    "puta",
    "puta que pariu",
    "puta que te pariu",
    "queca",
    "sacanagem",
    "saco",
    "torneira",
    "transar",
    "vadia",
    "vai - te foder",
    "vai tomar no cu",
    "veado",
    "vibrador",
    "xana",
    "xochota",
]

export default badWordsList